# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='tittle',
            new_name='title',
        ),
    ]
